#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-fakeweb
Version  : 1.3.0
Release  : 6
URL      : https://rubygems.org/downloads/fakeweb-1.3.0.gem
Source0  : https://rubygems.org/downloads/fakeweb-1.3.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-metaclass
BuildRequires : rubygem-mocha
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= FakeWeb
FakeWeb is a helper for faking web requests in Ruby. It works at a global
level, without modifying code or writing extensive stubs.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n fakeweb-1.3.0
gem spec %{SOURCE0} -l --ruby > rubygem-fakeweb.gemspec

%build
export LANG=C
gem build rubygem-fakeweb.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
fakeweb-1.3.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/fakeweb-1.3.0
ruby -v -I.:lib:test test*/test_*.rb || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/fakeweb-1.3.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/CHANGELOG
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/fakeweb.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/lib/fake_web.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/lib/fake_web/ext/net_http.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/lib/fake_web/registry.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/lib/fake_web/responder.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/lib/fake_web/response.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/lib/fake_web/stub_socket.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/lib/fake_web/utility.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/lib/fakeweb.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/fixtures/google_response_from_curl
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/fixtures/google_response_with_transfer_encoding
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/fixtures/google_response_without_transfer_encoding
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/fixtures/test_example.txt
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/fixtures/test_txt_file
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_allow_net_connect.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_deprecations.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_fake_authentication.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_fake_web.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_fake_web_open_uri.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_last_request.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_missing_open_uri.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_missing_pathname.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_other_net_http_libraries.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_precedence.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_query_string.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_regexes.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_response_headers.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_trailing_slashes.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/test_utility.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/right_http_connection-1.2.4/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/right_http_connection-1.2.4/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/right_http_connection-1.2.4/README.txt
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/right_http_connection-1.2.4/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/right_http_connection-1.2.4/lib/net_fix.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/right_http_connection-1.2.4/lib/right_http_connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/right_http_connection-1.2.4/setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/.document
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/lib/samuel.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/lib/samuel/net_http.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/lib/samuel/request.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/samuel.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/test/request_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/test/samuel_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/fakeweb-1.3.0/test/vendor/samuel-0.2.1/test/thread_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/fakeweb-1.3.0.gemspec
